name: Create Infrastructure and Run Docker Image

on:
  workflow_dispatch:
    inputs:
      IMAGETAG:
        description: 'Image tag for the Docker image'
        required: true
        default: '1.0.0'

jobs:
  create_infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./iac

      - name: Apply Infrastructure
        run: terraform apply -auto-approve
        working-directory: ./iac

  run-docker-image:
    needs: create_infra
    uses: Davidsdaw/Portfolio-Cloud/actions/workflows/reusable-upload-to-ecr.yml@main
    with:
      IMAGETAG: ${{ github.event.inputs.IMAGETAG }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}